apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage
  subsets:
    - name: v1
      labels:
        version: v1
    - name: '1.1-SNAPSHOT'
      labels:
        version: 1.1-SNAPSHOT
    - name: '1.1-SNAPSHOT'
      labels:
        version: 1.1-SNAPSHOT
